#pragma config(Sensor, in2,    ,               sensorLineFollower)
#pragma config(Sensor, dgtl2,  ,               sensorTouch)
#pragma config(Sensor, dgtl3,  sonar,          sensorSONAR_cm)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Rina's code

/*
* port2 is the right side motor.
* port3 is the left side motor.
*/

/*
* speedOne is the slowest speed.
* speedTwo is the medium speed.
* speedThree is the fastest speed.
*/

task main()
{
	//Pressing the button will start the robot
	untilBump(dgtl2);
	wait(1);

	//Move foward (speedOne)
	startMotor(port2, 25);
	startMotor(port3, 25);
	wait(.5);
	//speedTwo
	startMotor(port2, 75);
	startMotor(port3, 75);
	wait(.3);
	//speedThree
	startMotor(port2, 150);
	startMotor(port3, 150);

	//Slow down (speedTwo)
	untilSonarLessThan(40,dgtl3);
	startMotor(port2, 75);
	startMotor(port3, 75);
	//speedOne
	untilSonarLessThan(20,dgtl3);
	startMotor(port2, 25);
	startMotor(port3, 25);

	//Move backwards
	untilTouch(dgtl2);
	wait(1);

	//Turn
	startMotor(port2, -55);
	wait(5);

	//Move foward(speedOne)
	startMotor(port2, 25);
	startMotor(port3, 25);
	wait(.5);
	//speedTwo
	startMotor(port2, 75);
	startMotor(port3, 75);
	wait(.3);
	//speedThree
	startMotor(port2, 150);
	startMotor(port3, 150);
	//Slow down (speedTwo)
	untilSonarLessThan(40,dgtl3);
	startMotor(port2, 75);
	startMotor(port3, 75);
	//speedOne
	untilSonarLessThan(20,dgtl3);
	startMotor(port2, 25);
	startMotor(port3, 25);
}
