#pragma config(Sensor, in2,    ,               sensorLineFollower)
#pragma config(Sensor, dgtl2,  ,               sensorTouch)
#pragma config(Sensor, dgtl3,  sonar,          sensorSONAR_cm)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	untilBump(dgtl2);
	wait(1);

	//this will start the robot
	startMotor(port2, 100);
	startMotor(port3, 115);
	untilSonarLessThan(30,dgtl3);
	//the motor slows down
	startMotor(port2, 50);
	startMotor(port3, 65);
	untilTouch(dgtl2);
	wait(1);
	//forward until it hits the first wall
	startMotor(port2, -55);
	wait(5);
	//pivots to make 90deg. turn
	startMotor(port2, 100);
	startMotor(port3, 115);
	untilSonarLessThan(30,dgtl3);
	//forward until 30cm away
	startMotor(port3, 55);
	wait(8);
	//turns almost 180deg.




}
